### ISSUE TITLE
Not working on course homepage

### ISSUE THREAD

**Issue by Rohaanpk** [JamesNZL/notion-assignment-import#66]
Extension does not work on course homepage 
(url example https://canvas.auckland.ac.nz/courses/72860)
Must open a subpage 
(url example https://canvas.auckland.ac.nz/courses/72860)
or add forward-slash after homepage link
(url example https://canvas.auckland.ac.nz/courses/72860/)

**Comment by JamesNZL** [comment]
![image](https://user-images.githubusercontent.com/44986932/180896478-12f1759f-53e6-4a58-af6c-941294b93123.png)

![image](https://user-images.githubusercontent.com/44986932/180896487-025e5cad-c972-4a7a-8bf8-009ce25af3a6.png)

Whoops, I haven't made the trailing slash optional—thanks!

**Comment by JamesNZL** [comment]
Fixed by [b418a41](https://github.com/JamesNZL/notion-assignment-import/commit/b418a419337bc91b8fd0efc4a0e6deb135d72837), I'll run a patch release later tonight.

Cheers ✨
